### ISSUE TITLE
Clean up `TextTokenizer` logic

### ISSUE THREAD

**Issue by weihua916** [pyg-team/pytorch-frame#216]
Currently, we are doing hacking around [here](https://github.com/pyg-team/pytorch-frame/blob/master/torch_frame/data/mapper.py#L296-L305). We should remove this hack.

**Comment by zechengz** [comment]
Actually I take a second look, as shown in the text example https://github.com/pyg-team/pytorch-frame/blob/b8d8d56a1c240e39e0ae47be06c0306776fb9c07/examples/transformers_text.py#L102-L104
where each tensor (values of `inputs`) is a 2 dimensional tensor if tokenizer receives a list of sentences but it will return a 1 dimensional tensor if tokenizer receives just one sentence. So, I think we should support both `dim=1` and `dim=2` tensors. WDYT?

**Comment by weihua916** [comment]
I think we can decompose this 2d tensor into 1d tensor using for-loop. We do for-loop anyway. I think it's better to be transparent and do for-loop here rather than inside our package. What do you think?

**Comment by zechengz** [comment]
Just to double check you mean we should do for loop in the text tokenizer such as here https://github.com/pyg-team/pytorch-frame/blob/b8d8d56a1c240e39e0ae47be06c0306776fb9c07/examples/transformers_text.py#L102-L104 instead of the mapper? IMO it's natural to just return tokens / masks in 2D tensor and we can help to handle in the mapper.

**Comment by weihua916** [comment]
Yes, for-loop here instead of inside `TensorMapper`.

**Comment by weihua916** [comment]
We aligned that we will define
```python
TextTokenizationOutputs = Union[List[Dict[str, Tensor]], Dict[str, Tensor]]
```
and implement a logic for `Dict[str, Tensor]` accordingly.
